<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="Description" content="Ici le contenu">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="<?= RELATIVE_PATH['images']?>site/favicon-32x32.png">
    <link rel="stylesheet" type="text/css" href="<?= RELATIVE_PATH['css']?>style.css">
    <title>Amoureusement Vôtre</title>
</head>
<body>
<header>

</header>
<main class="container">
    <?php if (isset($template) && $template !== ""): ?>
        <?php include $template . '.phtml' ?>
    <?php endif; ?>
</main>
<footer>

</footer>
<script src="<?= RELATIVE_PATH['js']?>libraries/vue@2.6.0.js"></script>
<script src="<?= RELATIVE_PATH['js']?>main.js"></script>
<?php if ($menu === 'home'): ?>
    <script src="<?= RELATIVE_PATH['js']?>menu.js"></script>
    <script src="<?= RELATIVE_PATH['js']?>home.js"></script>
<?php elseif ($menu === 'album'): ?>
    <script src="<?= RELATIVE_PATH['js']?>album.js"></script>
<?php endif; ?>
</body>
</html>