<div id="wait_loading"></div>
<div id="cinema_background">
    <form id="login_form">
        <section id="ticket">
            <p><span class="cine">Séance :</span><span class="horaire">pass VIP 2021</span> </p>
            <label class="cine" for="loginPassword_input">N° de ticket :</label>
            <input class="lieu" id="loginPassword_input" name="password" type="password"  maxlength="60" value="" placeholder="?">
            <label class="cine" for="loginEmail_input">Email :</label>
            <input class="lieu" id="loginEmail_input" name="email" type="text"  maxlength="100" value="" placeholder="?">
            <h1>Amoureusement vôtre <span class="vf">(VF)</span></h1>
            <div class="errorMessage" id="errorLogin_div"></div>
            <button class="submitButton" id="login_button" type="submit" onclick="testLogin()">Entrer</button>
            <div class="code">Charlotte et Tanguy se marient</div>
        </section>
    </form>
</div>
<div id="curtain"></div>